-- =====================================================================
-- 01  Roles, warehouse, schema
-- Run once as ACCOUNTADMIN (or SECURITYADMIN + SYSADMIN).
-- Replace ANALYTICS / DBT_DOCS / MY_DBT_PROJECT names to suit.
-- =====================================================================
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS DBT_DOCS_ADMIN;   -- owns repo, stage, proc, task, app
CREATE ROLE IF NOT EXISTS DBT_DOCS_VIEWER;  -- people who open the app
GRANT ROLE DBT_DOCS_ADMIN TO ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS DBT_DOCS_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE DBT_DOCS_WH TO ROLE DBT_DOCS_ADMIN;
GRANT USAGE ON WAREHOUSE DBT_DOCS_WH TO ROLE DBT_DOCS_VIEWER;

CREATE SCHEMA IF NOT EXISTS ANALYTICS.DBT_DOCS;
GRANT USAGE ON DATABASE ANALYTICS TO ROLE DBT_DOCS_ADMIN;
GRANT USAGE ON DATABASE ANALYTICS TO ROLE DBT_DOCS_VIEWER;
GRANT USAGE ON SCHEMA ANALYTICS.DBT_DOCS TO ROLE DBT_DOCS_VIEWER;
GRANT ALL ON SCHEMA ANALYTICS.DBT_DOCS TO ROLE DBT_DOCS_ADMIN;

-- Let the admin role run docs generate on your existing dbt project object.
-- (The project object is deployed from your dbt repo / workspace.)
GRANT USAGE   ON DATABASE ANALYTICS                       TO ROLE DBT_DOCS_ADMIN;
GRANT USAGE   ON SCHEMA   ANALYTICS.DBT                   TO ROLE DBT_DOCS_ADMIN;
GRANT USAGE   ON DBT PROJECT ANALYTICS.DBT.MY_DBT_PROJECT TO ROLE DBT_DOCS_ADMIN;
GRANT MONITOR ON DBT PROJECT ANALYTICS.DBT.MY_DBT_PROJECT TO ROLE DBT_DOCS_ADMIN;

-- Tasks
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DBT_DOCS_ADMIN;

-- Add people:  GRANT ROLE DBT_DOCS_VIEWER TO USER <user>;
